### PR TITLE
Fix when $userCurrencyCode was null

### PR DESCRIPTION
**Pull request by DenisNatalevich**

### CODE REVIEW

**Comment by ioan-ghisoi-cko** [comment]
@DenisNatalevich  Can you provide an example use-case for when the currency would be null?

**Comment by DenisNatalevich** [comment]
In my case, this happened in the multiview store side.

**Comment by david-fiaty-cko** [comment]
@DenisNatalevich, a quote with null currency code should never happen when it's time for a user to perform a payment action. Even a free order with amount 0 should have a currency. 

Could you please provide more details on how the quote or order happens to have no currency at the payment stage?

**Comment by david-fiaty-cko** [comment]
This code could cause major issues by allowing to process transactions that shouldn't be processed because of a missing currency. 

In the case of this PR, the fix would just add USD to any amount, cause the customer to be charged an amount higher than expected, or the merchant to receive an amount lower than expected.

Closing the PR for now, please reopen if needed.

**Pull request closed without merging**
